export default {
  MARK_NOTIFICATIONS_ASREAD: 'MARK_NOTIFICATIONS_HASREAD',
  MARK_ALL_NOTIFICATIONS_ASREAD: 'MARK_ALL_NOTIFICATIONS_ASREAD',
  START_LOADING: 'START_LOADING',
  END_LOADING: 'END_LOADING',
  GET_ALL_NOTIFICATIONS: 'GET_ALL_NOTIFICATIONS',
  START_LOGIN: 'START_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  CHANGE_AVATAR: 'CHANGE_AVATAR'
}
