export default {
  MARK_NOTIFICATIONS_ASREAD: 'MARK_NOTIFICATIONS_HASREAD',
  MARK_ALL_NOTIFICATIONS_ASREAD: 'MARK_ALL_NOTIFICATIONS_ASREAD',
  START_LOADING: 'START_LOADING',
  END_LOADING: 'END_LOADING',
  GET_ALL_NOTIFICATIONS: 'GET_ALL_NOTIFICATIONS'
}
